### ISSUE TITLE
저장소에 .gitignore 추가하는게 어떨지 ㅎㅎ

### ISSUE THREAD

**Issue by fabichoi** [ryeongee/Frontend_Study#1]
저장소를 보니 .DS_Store 같은 운영체제 파일(MacOS)가 있는거 같은데
메인에 .gitignore를 추가하는 편이 어떨지 제안 dream.

**Comment by ryeongee** [comment]
> 저장소를 보니 .DS_Store 같은 곳 파일 (MacOS)가 있는거 같은데
> 메인에 .gitignore를 추가하는 편이 어떨지 제안 dream.

감사합니다 ㅎㅎ
